# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('años_de_duracion', models.PositiveSmallIntegerField(verbose_name='años de duracion')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='apellido')),
            ],
            options={
                'verbose_name': 'secretario',
                'verbose_name_plural': 'secretarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='secretario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carreras', to='app_creditos.Secretario', verbose_name='Secretario'),
        ),
    ]
