# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
