# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0002_carrera_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('legajo', models.IntegerField(max_length=4, primary_key=True, serialize=False, verbose_name='legajo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('dni', models.PositiveIntegerField(max_length=8, verbose_name='dni')),
                ('mail', models.EmailField(max_length=255, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alumnos', to='app_creditos.Carrera', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'ordering': ['nombre'],
            },
        ),
    ]
