# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0003_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.BigIntegerField(max_length=8, verbose_name='dni'),
        ),
    ]
