# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0004_auto_20160506_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alumnos', to='app_creditos.Carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.BigIntegerField(verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='legajo'),
        ),
    ]
