# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0005_auto_20160506_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='cantidad_alumnos',
            field=models.IntegerField(null=True),
        ),
    ]
