# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0006_carrera_cantidad_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
