# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0007_secretario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('creditos', models.PositiveSmallIntegerField(verbose_name='creditos')),
                ('año', models.PositiveSmallIntegerField(verbose_name='año')),
            ],
            options={
                'verbose_name_plural': 'materias',
                'ordering': ['nombre'],
                'verbose_name': 'materia',
            },
        ),
    ]
