# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0008_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='correlativas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Materias', to='app_creditos.Materia', verbose_name='Materia'),
        ),
    ]
