# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0009_materia_correlativas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='correlativas',
        ),
        migrations.AddField(
            model_name='materia',
            name='correlativas',
            field=models.ManyToManyField(null=True, related_name='Materias', to='app_creditos.Materia', verbose_name='Materia'),
        ),
    ]
