# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0010_auto_20160506_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='correlativas',
            field=models.ManyToManyField(blank=True, related_name='correlacion', to='app_creditos.Materia', verbose_name='correlativas'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='nombre'),
        ),
    ]
