# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0012_auto_20160613_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='cantidad_alumnos',
        ),
    ]
