# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0013_remove_carrera_cantidad_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretario',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='nombre y apellido'),
        ),
    ]
